# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Doruk Çetin
author: Doruk Çetin
email: doruk.cetin.dc@gmail.com
inst-email: dcetin@student.ethz.ch
prev-email: doruk.cetin@metu.edu.tr
description: >-
  Tis but a personal website.

baseurl: ""
url: "http://dorukcetin.me/"
lang: en_US

github_username:  dcetin
linkedin_username: doruk-cetin
letterboxd_username: Mirakodus
spotify_username: "11145656283"
instagram_username: "drkcetin"
gscholar_username: "xbYfOpAAAAAJ"
# https://dblp.uni-trier.de/pers/hd/c/Cetin:Doruk

social:
  name: Doruk Çetin
  links:
    - https://www.linkedin.com/in/doruk-cetin
    - https://github.com/dcetin
    - https://letterboxd.com/Mirakodus
    - https://open.spotify.com/user/11145656283

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# - jekyll-email-protect

header_pages:
  - "contact.md"
  - "cv.md"
  - "publications.md"
  - "personal.md"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
